### PR TITLE
FIX: issue with letterhead not appearing

### PR DESCRIPTION
**Pull request by fabianp**
just moved it outside of the \maketitle block and it seems to work, both on my machine and overleaf

### CODE REVIEW

**Comment by fabianp** [comment]
I also added to the .tex "To de-anonymize and remove mentions
to TMLR (for example for posting to preprint servers), use the preprint option,
as in {\tt {\textbackslash}usepackage[preprint]\{tmlr\}}. "

**Comment by larocheh** [comment]
While we're at it, can you also adjust that comment in tmlr.tex that mentions the old macro: \tmlrfinalcopy

% Authors must not appear in the submitted version. They should be hidden
% as long as the \tmlrfinalcopy macro remains commented out below.
% Non-anonymous submissions will be rejected without review.

**Comment by fabianp** [comment]
sounds good. I replaced it with 
```
% Authors must not appear in the submitted version. They should be hidden
% as long as the tmlr package is used without the [accepted] or [preprint] options.
% Non-anonymous submissions will be rejected without review.
```

**Comment by larocheh** [comment]
Sorry, one last thing :-) 

Can you also add this comment, below the description of how to use the [accepted] option?

% To de-anonymize and remove mentions to TMLR (for example for posting to preprint servers), instead use the following:
%\usepackage[preprint]{tmlr}

**Comment by fabianp** [comment]
sure, done

**Comment by fabianp** [comment]
merged

**Pull request merged**
